version: '3.9'

services:
  db:
    image: postgres:14.8-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    

  backend:
    image: aragon1025/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app_backend/static/
      - media_value:/app_backend/media/
      - redoc:/app/docs/
    depends_on:
      - db
    env_file: .env

  frontend:
    image: aragon1025/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    depends_on:
      - backend
    volumes:
      - ./frontend/:/app/
      - static_value:/frontend_static/
      - media_value:/app/media/


  nginx:
    image: aragon1025/foodgram_gateway
    restart: always 
    env_file: .env
    ports:
      - 8000:80
    depends_on:
      - frontend
    volumes:
      - static_value:/staticfiles/
      - media_value:/media/
      - redoc:/app/docs/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/

volumes:
  postgres_data:
  static_value:
  media_value:
  redoc:

